Update first_workflow.yml
adding error

diff --git a/.github/workflows/first_workflow.yml b/.github/workflows/first_workflow.yml
--- a/.github/workflows/first_workflow.yml
+++ b/.github/workflows/first_workflow.yml
@@ -10,3 +10,6 @@ jobs:
       - uses: actions/checkout@v3
       - name: Running a simple Github Action
         run: echo "this workflow needs to run"
+        
+      - name: simulating error
+        run: echo "error taking place"; exit 1
